import type { PortfolioContent } from '@/lib/notion/schemas'
import fallbackContent from './fallback-content.json'
import notionContent from './notion-content.json'

// `notion-content.json` is regenerated by scripts/fetch-notion-content.ts on
// every build (the prebuild npm script). If Notion is unreachable or
// credentials are missing, that script copies fallback-content.json into
// place — so this import always succeeds with something.
//
// Previously this used `require('./notion-content.json')` inside a try/catch.
// Vite has no `require` in its ESM bundle, so the catch branch always ran
// and the site silently rendered fallback-content.json instead of live
// Notion content. ES import + a sanity check fixes that.
const content: PortfolioContent =
  notionContent && Object.keys(notionContent).length > 0
    ? (notionContent as unknown as PortfolioContent)
    : (fallbackContent as PortfolioContent)

export const portfolioContent = content

// Named exports for convenience
export const siteConfig = content.siteConfig
export const contactInfo = content.contact
export const skills = content.skills
export const projects = content.projects
export const experience = content.experience
export const education = content.education
export const heroContent = content.hero
export { RESUME_PATH } from '@/constants'

// Re-export types
export type {
  PortfolioContent,
  SiteConfig,
  ContactInfo,
  Skills,
  Project,
  Experience,
  Education,
  HeroContent
} from '@/lib/notion/schemas'
